#!/usr/bin/php
<?php

require_once __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Symfony\Component\Dotenv\Dotenv;

$dotenv->load(__DIR__.'/.env');
echo getenv();
$application = new Application();

// ... register commands

$application->run();